# Generated by Django 5.1.5 on 2025-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='action_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
