# Generated by Django 5.1.5 on 2025-01-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_step_action_time_step_wait_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='duration',
        ),
        migrations.AlterField(
            model_name='step',
            name='action_time',
            field=models.IntegerField(),
        ),
    ]
