# Generated by Django 5.1.5 on 2025-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_step_duration_alter_step_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.CharField(choices=[('cut', '切る'), ('boil', '煮る'), ('grill', '焼く'), ('steam', '蒸す'), ('fry', '揚げる'), ('boil_water', '茹でる'), ('cook_rice', '炊く'), ('stir_fry', '炒める'), ('mix', '和える'), ('microwave', '電子レンジ')], max_length=20),
        ),
    ]
