# Generated by Django 5.1.5 on 2025-01-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_step_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='wait_time',
        ),
    ]
