# Generated by Django 5.1.5 on 2025-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_step_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
