# Generated by Django 5.1.5 on 2025-01-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_step_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='action',
            field=models.CharField(choices=[('cut', '切る'), ('boil', '煮込む'), ('grill', '焼く'), ('steam', '蒸す'), ('fry', '揚げる'), ('boil_water', '茹でる'), ('cook_rice', '炊く'), ('stir_fry', '炒める'), ('mix', '混ぜる'), ('toss', '和える'), ('pack', '詰める'), ('microwave', '電子レンジ'), ('arrangement', '盛り付け')], max_length=20),
        ),
    ]
