# Generated by Django 5.1.5 on 2025-01-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_step_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='order',
            new_name='number',
        ),
    ]
